### ISSUE TITLE
polymut.py script does not work properly

### ISSUE THREAD

**Issue by VadimDu** [SegataLab/cmseq#1]
Dear developer / SegataLab,

Thank you for the useful tool!

The poly.py worked great for my MAGs analysis for SNPs, however the polymut.py did not work.
You have written in the doc: "Please supply a gff file from roary and make sure that the contig names between the bam file and the gff file can be matched.".
Roary does not output a gff file, but rather Prokka produce gff file that can be used with Roary - is this what you meant? (this gff file has both gene annotations and the nucleotide sequence of the contigs). I have confiremd the matching of the contigs header.

When I run polymut.py with the bam and gff files of my MAG, after 10-20min it finished without any errors, but the output file had just 3 numbers in a single line (65.0 79.0 4169686.0).

Any ideas / advises will be greatly welcomed.

Lastly, for CMSeq requirements need to be added: Bio and bcbio-gff modules.

Best regards
Vadim

**Comment by azufre451** [comment]
Hi Vadim, 

You are right, the gff files required by polymut.py are from Prokka and not from Roary. I will correct this in the documentation. I will also add the missing requirements.

Does your output contain any reference to the entries you have in the bam file? Have you tried to specify one single MAG by using the -c option of polymut?

**Comment by VadimDu** [comment]
Hi Moreno,

Thank you for the quick response.

I have tried as you suggested to specify only specific contigs with -c, but I'm keep getting the following warnings:
/cmseq-master/cmseq.py:154: UserWarning: 54 is not tracked by the BAMFile.
  warnings.warn(str(rec.id) + " is not tracked by the BAMFile.")
My contigs have headers as numbers (1,2,3,...54) - they appear like this in both the BAM file and in the gff file. I'm getting this warning for all the NOT specified contigs by -c option, and in the end some numerical output in one line (0.0 4.0 217743.0).
Any ideas why this happens?

Thanks again
Vadim

**Comment by VadimDu** [comment]
@azufre451 Hi again,

Any response on the topic? The polymut.py just does not work for me, I've tried it with different contigs from different assemblies, even have simplified the contigs names (just to >0 >1 >2 etc).
I am providing as instructed a GFF file from Prokka + BAM file (sorted and indexed) from the read mapping to the contigs.
I will just add the poly.py script works just fine - so I suspect it has to do something with the GFF file.

These is an example of the last error I got:

Traceback (most recent call last):
  File "/urigo/vadimd/cmseq-master/polymut.py", line 41, in <module>
    polymut_from_file(parser.parse_args())
  File "/urigo/vadimd/cmseq-master/polymut.py", line 22, in polymut_from_file
    bf.parse_gff(args.gff_file)
  File "/urigo/vadimd/cmseq-master/cmseq.py", line 136, in parse_gff
    gene_seq = rev_comp(rec.seq[indices[0]:indices[1]])
  File "/urigo/vadimd/cmseq-master/cmseq.py", line 104, in rev_comp
    bases = [complement[base] for base in bases]
  File "/urigo/vadimd/cmseq-master/cmseq.py", line 104, in <listcomp>
    bases = [complement[base] for base in bases]
KeyError: '?'

Your help will be appreciated,
Vadim

**Comment by azufre451** [comment]
Hi Vadim,

the output you see from polymut.py is a summary of all the contigs (i.e. -c) that you analyze.
From the example you have 336 DNs (non syn. SNPs), 914 DSs (syn. SNPs) and this is computed on a total of 3,560,139 positions (nucleotides)

If you want to separate your stats for different groups of genomes, you need to do so by running polymut.py separately with the -c option tuned accordingly (that is, each time with the group of contigs you want to analyze).

Poly.py, instead, will compute the SNVs rate regardless of any ORF-prediction (hence, with that you cannot discriminate between synonymous and non-synonymous variants).

Hope this helps, let me know if you need any other assistance!

Best,
Moreno

**Comment by azufre451** [comment]
Hi tenlives, you can find the example [here](https://github.com/SegataLab/cmseq/blob/master/README.md#examples-1) in the documentation.

Also, the documentation has been extended so to better explain the usage of polymut.py.

best,
Moreno
