### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by boydgreenfield** [SegataLab/cmseq#6]
Hi folks – while [Conda shows this project as MIT-licensed](https://anaconda.org/bioconda/cmseq) (and I know that's what you've typically used), there is not a `LICENSE` file in the repository nor in `setup.py`. 

Could you clarify the intended license and add a file/line to `setup.py` as appropriate? Many thanks!

**Comment by azufre451** [comment]
All done! I updated the setup.py and added a license file to the repo.
